### ISSUE TITLE
Indices of telescope dictionary for photo-electrons shifted by 1

### ISSUE THREAD

**Issue by tino-michael** [cta-observatory/pyhessio#26] opened 2016-05-03 14:55 UTC
I tried to compare the camera response to the number of photo-electrons from a noiseless shower sample I generated myself. I noticed that the enumeration of the telescope IDs between the two containers is shifted by 1: The photo-electron image for "telescope 1" actually belongs to telescope 2 (see attached plot).

Please keep in mind that only triggered telescopes are stored in the file so that this problem is not easily fixed down the analysis chain by simply offsetting one index.

e.g. If **only** telescope 6 would be hit, the photo-electrons of telescope 5 are saved (which are empty) but not the ones of telescope 6; this information is lost.

![telescopeindexing_mismatch](https://cloud.githubusercontent.com/assets/18286015/14987063/c0b434e6-114e-11e6-970b-82bf664bdc94.png)

**Comment by jacquemier** [comment] 2016-05-03 15:02
How do you obtain these two containers ?
Do you have some code that I can execute to reproduce the bug before to correct it ?

**Comment by tino-michael** [comment] 2016-05-03 15:35
I get the detector response with 
_event.dl0.tel[tel_id].adc_sums[0]_
and the PEs with the just merged
_event.mc.tel[tel_id].photo_electrons_

Attached is a minimal working example.
You will have to change the name of the data file of course.

• adapted from read_hessio.py in ctapipe/examples
• renamed to .txt so the upload does not complain
[TelID_mismatch_minimal.txt](https://github.com/cta-observatory/pyhessio/files/247203/TelID_mismatch_minimal.txt)

**Comment by jacquemier** [comment] 2016-05-04 07:42
What about out guessPixDirection ?
Is it a local file in your filesystem ?

**Comment by jacquemier** [comment] 2016-05-04 07:57
On my system, it seems to correct

![figure_1](https://cloud.githubusercontent.com/assets/13165509/15008120/4dbaec6a-11de-11e6-9e31-80df3278247d.png)

Which version of pyhessio are you using ? (I am using '0.5.4')

**Comment by tino-michael** [comment] 2016-05-04 11:18
> What about out guessPixDirection ?
> Is it a local file in your filesystem ?
Yes, sorry, I thought I removed everything...

> Which version of pyhessio are you using ?
Where do I find the version number? I'm on the latest git version, though...
Just found this:

> $ cat meta.yaml 
> package:
>   name: pyhessio
>   version: 0.5.4

**Comment by jacquemier** [comment] 2016-05-04 12:20
>> What about out guessPixDirection ?
>> Is it a local file in your filesystem ?

>Yes, sorry, I thought I removed everything...
It does not matter as code runs without it.

>> Which version of pyhessio are you using ?

>Where do I find the version number? I'm on the latest git version, though...
>Just found this:

>> $ cat meta.yaml 
>> package:
>>  name: pyhessio
>>  version: 0.5.4


I do not understand for the time being, why we do not obtain the same result.
Can you try to reinstall last version of pyhessio and ctapipe to test if you can reproduce the bug ?

**Comment by tino-michael** [comment] 2016-05-04 12:50
Can you try the file that I produced?
https://www.dropbox.com/s/jja5q2ikve4dcsa/gamma_20deg_180deg_run10___cta-prod3-demo_desert-2150m-Paranal_Tino_pureSignal_cone10.simtel.gz?dl=1

I'm afraid it's a problem at the stage the file is written (latest when the empty telescopes are thrown away) and not read back in.

**Comment by jacquemier** [comment] 2016-05-04 13:20
![figure_1-2](https://cloud.githubusercontent.com/assets/13165509/15015281/3ba1cc10-120b-11e6-90ef-624e4a938aea.png)
It is also working on my system with your file.
I  just realized that pyhessio version is not enough, because this version is not increment before each PULL Request.

**Comment by jacquemier** [comment] 2016-05-04 13:36
Watsonjj PULL REQUEST #25 has modified get_mc_number_photon_electron method. 
AND it also  fixes a bug where the telescope_id was being used where telescope_index.
This may be the bug you  encounter now !

**Comment by tino-michael** [comment] 2016-05-04 13:38
you are now plotting the ADC container twice...
Since I couldn't get the event display to accept the PE container, I am overwriting the ADC array with the PE array pixel by pixel. Please make sure that you use the most current ctapipe version (which I submitted and you merged) since there was bug with the PE container.

> This may be the bug you encounter now !

I did a pull this morning... I will try again.

**Comment by jacquemier** [comment] 2016-05-04 13:49
After ctapipe uptate:
With your file:
![event5309](https://cloud.githubusercontent.com/assets/13165509/15016077/a4671c56-120f-11e6-830d-0954c35122fc.png)

With official PROD3 (gamma_20deg_0deg_run9408___cta-prod3-merged_desert-2150m-Paranal-subarray-4_cone10.simtel.gz)
![event 37016](https://cloud.githubusercontent.com/assets/13165509/15016086/b38df7d6-120f-11e6-8207-1b8d630594c3.png)

**Comment by tino-michael** [comment] 2016-05-04 14:01
yes I think I got it.

In my pyhessio directory, I pulled the current version, issued a
> python setup.py build
> python setup.py install

without any changes. It didn't seem to update my installation. I cloned a new copy of pyhessio, build and installed it and then the PE image was blank as with you.

reverting the "bugfix" I submitted, I get this
![telescopeindexing_mismatch_v2](https://cloud.githubusercontent.com/assets/18286015/15016401/1c28d6ac-1211-11e6-8106-00d3e706d933.png)

Which seems fine.

So, the problem seems to be that pyhessio didn't update after the pull and I "fixed" something in ctapipe that was already been taken care of on the other end.

**Comment by jacquemier** [comment] 2016-05-04 14:33
Good job ! I confirm that I can reproduce it on my system.
Could you please make a new PULL REQUEST on ctapipe to revert the "bugfix" you submitted ?

**Closed by jacquemier** 2016-05-04 14:33 UTC

**Comment by tino-michael** [comment] 2016-05-04 14:45
Looking at the _get_mc_number_photon_electron_ function within pyhessio I noticed that the pixel_id is no longer used and the function now returns one array with the PEs for all pixel on the telescope.
The loop over the pixel index in ctapipe/io/hessio.py is therefore superfluous....
I can remove the loop and leave a dummy pixel_id in the function call.
But maybe somebody wants to fix the interface altogether.
